theme: jekyll-theme-minimal

title: Christopher Hannan
description: I love learning how to modernise network operations with an automated DevOps infrastructure as code (IaC) approach.

urls:
    linkedin: https://www.linkedin.com/in/1chrishannan/
    github: https://github.com/cphannan

contacts:
    email: channan@hotmail.co.uk

motto: Nothing great in the world has ever been accomplished without passion. - Georg Wilhelm Friedrich Hegel